### ISSUE TITLE
友代问，sdk 7.0 按照教程添加没效果？

### ISSUE THREAD

**Issue by darknessomi** [molon/MLTransition#10]
另外问：这个是什么意思 不会死循环吗
![image](https://cloud.githubusercontent.com/assets/6939375/5695561/0b41c592-99e5-11e4-8e81-f116047f907f.png)
自己调用自己。。
还是说内部break就好？

**Comment by darknessomi** [comment]
之前解决，UIScrollView怎么才能手势返回？

**Comment by molon** [comment]
@darknessomi    
* 看起来是自己调用自己，实际上不是。因为做了方法Swizzle。   
* UIScrollView的关于手势返回的相关处理在 UIScrollView(__MLTransistion) 类目里，请看下。当前处理的结局是，如果这个scrollView可以横向拖的话，就忽略了拖返，否则拖返有效。如果有其他的和当前实现不一样的，可继承UIScrollView并单独实现`gestureRecognizer:shouldRequireFailureOfGestureRecognizer:`协议方法。
