### ISSUE TITLE
键盘弹起的时候，拖动返回会有问题

### ISSUE THREAD

**Issue by pomin** [molon/MLTransition#11]
键盘弹起的的时候，拖动返回，键盘会一直留在界面上。
![screen shot 2015-01-29 at 10 23 43](https://cloud.githubusercontent.com/assets/161920/5951355/3abaf7e8-a7a1-11e4-802b-1be7497e4704.png)

参考系统的实现，键盘会随着拖动一起被拖走。
![screen-shot-2015-01-29-at- 10 28 48](https://cloud.githubusercontent.com/assets/161920/5951422/5ac44f66-a7a2-11e4-952e-900b9114611a.png)

**Comment by molon** [comment]
@pomin 其实系统的那个信息键盘跟着拖返我猜测应该是做了特殊的处理。 你可以写个demo看下iOS7原生边界拖返的效果。现在库里的这种效果是iOS7原生边界拖返的效果一样的。
如果需要像信息那样跟着拖返。我并没有做过，但是可以获取键盘view，然后通过KVO去同步位置，当然这只是我的一时间想法并没有去实验，不确保效果OK。:)

**Comment by pomin** [comment]
@molon https://github.com/cotap/TAPKeyboardPop 昨天Google这个问题后看到这样一个库，还没来得整合到你的库里面。先贴出来标记一下。

**Comment by molon** [comment]
@pomin 感谢分享，似乎看起来很屌的样子，有空我也研究下。
