### ISSUE TITLE
UIScrollView与手势返回

### ISSUE THREAD

**Issue by chenqihui** [molon/MLTransition#12]
您好，请问如果在子页面上使用UIScrollView，它是横向滑动的（例如查看照片等），当滑动到边缘继续滑动，活着在UIScrollView边缘直接滑动，此时如何调用手势返回？大概就想知道UIScrollView边缘滑动如何传递给手势返回！？

**Comment by molon** [comment]
@chenqihui 可以参考下MLBlackTransition.m里的@interface UIScrollView(__MLTransistion) 这块代码。这个虽然不是适合你的需求，但是原理上是一样的。 你只要检测当前scrollView contentOffset是否到了边界，如果是则把pan手势优先级搞成比拖返手势低，这样就会执行了拖返。(这个效果的话，应该只会在scrollView start pan的时候检测，而在panning时候即使发现到了边界，也不会进行拖返，可能不是太完美，但是我感觉已经达到了需求)   
我并没有验证我的说法，你可以尝试下。有问题再交流。:)
