### ISSUE TITLE
能否在某个控制器控制不让其右滑返回，除了Present当前控制器。

### ISSUE THREAD

**Issue by sauchye** [molon/MLTransition#14]
能否在某个控制器获取该右滑事件，控制不让其右滑返回，除了Present当前控制器。

**Comment by molon** [comment]
@sauchye 是想在某控制器禁用拖返？ `enabledMLTransition:` 方法就可以啊。

**Comment by molon** [comment]
`disableMLTransition` 是针对UIView的。

**Comment by sauchye** [comment]
@molon 非常感谢！已搞定。
