### ISSUE TITLE
关于使用系统NavigationBar 和 隐藏NavigationBar混用的时候？

### ISSUE THREAD

**Issue by HarrySu** [molon/MLTransition#15]
您好，当从系统NavigationBar 过度到自动以NavigationBar 的界面的时候就会出现上方的Navigation Bar隐藏了一节。我是在ViewWillDisAppear 里面写NavigationBar.Hidden = YES的。这个请问应该怎么解决？

**Comment by molon** [comment]
导航条隐藏切换的问题比较复杂，而且这个问题，即使不用此库也是会出现的。
具体请看下:https://github.com/molon/MLTransition/issues/13 最底部解释。:)

**Comment by molon** [comment]
@HarrySu https://github.com/molon/MLTransition/issues/13 最底部有更新方法。
