### ISSUE TITLE
侧滑返回当前页时  跑马灯label停止滚动了？

### ISSUE THREAD

**Issue by lihuichina** [molon/MLTransition#17]
侧滑返回当前页时  跑马灯label有时就停止滚动了？咋解决，我是用UIview

**Comment by molon** [comment]
@lihuichina 
- 有时就停止滚动？这个我蛮疑惑的，如果因为拖返动画打断的原因，肯定也是必定停止滚动的。
- 不使用此库，边界拖返的话也是会停止滚动的吧？因为动画的实施还是使用的原生机制。
- 你用的不是UIScrollView，按说不会是runloop相关问题。
- 实在不行，你可以尝试用 CADisplayLink 去实现跑马灯。
