### ISSUE TITLE
iOS 11 适配

### ISSUE THREAD

**Issue by YogaChen** [molon/MLTransition#18]
iOS 11 下设置导航栏透明没有效果

**Comment by molon** [comment]
@YogaChen 你说的这个问题和此库没有干系啊。此库只是开启了拖返罢了，没对导航条做任何处理的。

你是不是想问的 https://github.com/molon/MLNavigationBarTransition 这个啊

**Comment by YogaChen** [comment]
@molon 是的，不好意思，搞错了

**Comment by molon** [comment]
@YogaChen MLNavigationBarTransition的iOS11问题我也是刚解决，设置透明度那个方式有变化哈，以前那方式不行了，用ml_backgroundAlpha
