### ISSUE TITLE
當隱藏導航時候，使用這個庫發現如果頻繁的拖動一點點。會發現導航欄出現黑邊

### ISSUE THREAD

**Issue by zeqinjie** [molon/MLTransition#19]
如題

**Comment by molon** [comment]
@zeqinjie 隐藏导航这块本身iOS SDK里就有BUG，即使不用此库也如此。建议不要使用navigationBarHidden，如果有隐藏导航条的需求，请尝试改变导航条的透明度，或者尝试使用另外一个库
http://github.com/molon/MLNavigationBarTransition

**Comment by zeqinjie** [comment]
是否是修改preferredStatusBarStyle 樣式引起 http://www.jianshu.com/p/0f0d10009ba7。我這邊這樣處理就好了
