### ISSUE TITLE
只在Xcode Run的時候有作用

### ISSUE THREAD

**Issue by kkdayitbobson** [molon/MLTransition#20]
目前測試iOS 11, iOS 10在不使用Xcode 直接Run的情況下，MLTransition的手勢會沒有作用

**Comment by molon** [comment]
意思是iOS10和11两个系统非调试运行时候回失效么？

**Comment by kkdayitbobson** [comment]
是的

**Comment by molon** [comment]
@kkdayitbobson 哥们，并没有重现啊。先不说11，如果10有这问题，早该有人报给我了，你是不是有其他地方影响了啊。

**Comment by kkdayitbobson** [comment]
我昨天試的結果...發現 MLTransition 的viewDidLoad沒有被call到，詳細原因還要再找一下

**Comment by kkdayitbobson** [comment]
我找到原因了...，因為在專案中，有個 

`
extension UINavigationController
{
    open override func viewDidLoad() {
        // .......
    }
}
`

導致MLTransition viewDidLoad 沒有被call到....，目前把他刪除就好了
